FROM node:18-alpine

WORKDIR /app

# Copy catalogs
COPY package*.json ./

# Install dev dependencies
RUN npm install

# Copy code
COPY . .

# Expose Vite dev port
EXPOSE 5173

# Start Vite dev server
CMD ["npm", "run", "dev"]
